version: '3'
services: 
 web:
 build: .
 context: .
 dockerfile: Dockerfile
 command: gunicorn smappweb:oneloadpro --log-file - --bind 0.0.0.0:$PORT
ports: 
 -"$PORT:$PORT"
enviroment: 
 -PORT=5000

worker:
 build: .
command: celery -A oneloadpro worker --loglevel=info 
enviroment: 
 - BROKER_URL=amqp://rabbitmq
 - RESULT_BACKEND=amqp://rabbitmq

rabbitmq:
  image: rabbitmq:3-magnament
  ports: 
   -"5672:5672"
    -"15672:15672"